{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}

-- | Pretty-printer for CSimple.
--   Generated by the BNF converter.

module CSimple.Lang.Print where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, dropWhile, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified CSimple.Lang.Abs

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i = \case
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    [";"]        -> showChar ';'
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : ts@(p:_) | closingOrPunctuation p -> showString t . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i     = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t s =
    case (all isSpace t', null spc, null rest) of
      (True , _   , True ) -> []              -- remove trailing space
      (False, _   , True ) -> t'              -- remove trailing space
      (False, True, False) -> t' ++ ' ' : s   -- add space if none
      _                    -> t' ++ s
    where
      t'          = showString t []
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt     _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print CSimple.Lang.Abs.Id where
  prt _ (CSimple.Lang.Abs.Id (_,i)) = doc $ showString i
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print CSimple.Lang.Abs.Program where
  prt i = \case
    CSimple.Lang.Abs.PDefs defs -> prPrec i 0 (concatD [prt 0 defs])

instance Print [CSimple.Lang.Abs.Def] where
  prt = prtList

instance Print CSimple.Lang.Abs.Def where
  prt i = \case
    CSimple.Lang.Abs.DFun type_ id_ args stms -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_, doc (showString "("), prt 0 args, doc (showString ")"), doc (showString "{"), prt 0 stms, doc (showString "}")])
  prtList _ [] = concatD []
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print [CSimple.Lang.Abs.Arg] where
  prt = prtList

instance Print [CSimple.Lang.Abs.Stm] where
  prt = prtList

instance Print CSimple.Lang.Abs.Arg where
  prt i = \case
    CSimple.Lang.Abs.ADecl type_ id_ -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print CSimple.Lang.Abs.Stm where
  prt i = \case
    CSimple.Lang.Abs.SExp exp -> prPrec i 0 (concatD [prt 0 exp, doc (showString ";")])
    CSimple.Lang.Abs.SDecls type_ ids -> prPrec i 0 (concatD [prt 0 type_, prt 0 ids, doc (showString ";")])
    CSimple.Lang.Abs.SInit type_ id_ exp -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_, doc (showString "="), prt 0 exp, doc (showString ";")])
    CSimple.Lang.Abs.SReturn exp -> prPrec i 0 (concatD [doc (showString "return"), prt 0 exp, doc (showString ";")])
    CSimple.Lang.Abs.SWhile exp stm -> prPrec i 0 (concatD [doc (showString "while"), doc (showString "("), prt 0 exp, doc (showString ")"), prt 0 stm])
    CSimple.Lang.Abs.SIfElse exp stm1 stm2 -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 exp, doc (showString ")"), prt 0 stm1, doc (showString "else"), prt 0 stm2])
    CSimple.Lang.Abs.SBlock stms -> prPrec i 0 (concatD [doc (showString "{"), prt 0 stms, doc (showString "}")])
  prtList _ [] = concatD []
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print [CSimple.Lang.Abs.Id] where
  prt = prtList

instance Print CSimple.Lang.Abs.Exp where
  prt i = \case
    CSimple.Lang.Abs.EInt n -> prPrec i 15 (concatD [prt 0 n])
    CSimple.Lang.Abs.EDouble d -> prPrec i 15 (concatD [prt 0 d])
    CSimple.Lang.Abs.EString str -> prPrec i 15 (concatD [prt 0 str])
    CSimple.Lang.Abs.ETrue -> prPrec i 15 (concatD [doc (showString "true")])
    CSimple.Lang.Abs.EFalse -> prPrec i 15 (concatD [doc (showString "false")])
    CSimple.Lang.Abs.EId id_ -> prPrec i 15 (concatD [prt 0 id_])
    CSimple.Lang.Abs.ECall id_ exps -> prPrec i 15 (concatD [prt 0 id_, doc (showString "("), prt 0 exps, doc (showString ")")])
    CSimple.Lang.Abs.EPIncr exp -> prPrec i 14 (concatD [prt 15 exp, doc (showString "++")])
    CSimple.Lang.Abs.EPDecr exp -> prPrec i 14 (concatD [prt 15 exp, doc (showString "--")])
    CSimple.Lang.Abs.EIncr exp -> prPrec i 13 (concatD [doc (showString "++"), prt 14 exp])
    CSimple.Lang.Abs.EDecr exp -> prPrec i 13 (concatD [doc (showString "--"), prt 14 exp])
    CSimple.Lang.Abs.ENeg exp -> prPrec i 13 (concatD [doc (showString "-"), prt 14 exp])
    CSimple.Lang.Abs.EMul exp1 exp2 -> prPrec i 12 (concatD [prt 12 exp1, doc (showString "*"), prt 13 exp2])
    CSimple.Lang.Abs.EDiv exp1 exp2 -> prPrec i 12 (concatD [prt 12 exp1, doc (showString "/"), prt 13 exp2])
    CSimple.Lang.Abs.EAdd exp1 exp2 -> prPrec i 11 (concatD [prt 11 exp1, doc (showString "+"), prt 12 exp2])
    CSimple.Lang.Abs.ESub exp1 exp2 -> prPrec i 11 (concatD [prt 11 exp1, doc (showString "-"), prt 12 exp2])
    CSimple.Lang.Abs.ELt exp1 exp2 -> prPrec i 9 (concatD [prt 9 exp1, doc (showString "<"), prt 10 exp2])
    CSimple.Lang.Abs.EGt exp1 exp2 -> prPrec i 9 (concatD [prt 9 exp1, doc (showString ">"), prt 10 exp2])
    CSimple.Lang.Abs.ELEq exp1 exp2 -> prPrec i 9 (concatD [prt 9 exp1, doc (showString "<="), prt 10 exp2])
    CSimple.Lang.Abs.EGEq exp1 exp2 -> prPrec i 9 (concatD [prt 9 exp1, doc (showString ">="), prt 10 exp2])
    CSimple.Lang.Abs.EEq exp1 exp2 -> prPrec i 8 (concatD [prt 9 exp1, doc (showString "=="), prt 8 exp2])
    CSimple.Lang.Abs.ENeq exp1 exp2 -> prPrec i 8 (concatD [prt 9 exp1, doc (showString "!="), prt 8 exp2])
    CSimple.Lang.Abs.EAnd exp1 exp2 -> prPrec i 4 (concatD [prt 4 exp1, doc (showString "&&"), prt 5 exp2])
    CSimple.Lang.Abs.EOr exp1 exp2 -> prPrec i 3 (concatD [prt 3 exp1, doc (showString "||"), prt 4 exp2])
    CSimple.Lang.Abs.EAss exp1 exp2 -> prPrec i 2 (concatD [prt 3 exp1, doc (showString "="), prt 2 exp2])
    CSimple.Lang.Abs.ETyped exp type_ -> prPrec i 0 (concatD [doc (showString "["), prt 0 exp, doc (showString ":"), prt 0 type_, doc (showString "]")])
    CSimple.Lang.Abs.EConv type_ exp -> prPrec i 0 (concatD [doc (showString "("), prt 0 type_, doc (showString ")"), prt 0 exp])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [CSimple.Lang.Abs.Exp] where
  prt = prtList

instance Print CSimple.Lang.Abs.Type where
  prt i = \case
    CSimple.Lang.Abs.Tbool -> prPrec i 0 (concatD [doc (showString "bool")])
    CSimple.Lang.Abs.Tdouble -> prPrec i 0 (concatD [doc (showString "double")])
    CSimple.Lang.Abs.Tint -> prPrec i 0 (concatD [doc (showString "int")])
    CSimple.Lang.Abs.Tstring -> prPrec i 0 (concatD [doc (showString "string")])
    CSimple.Lang.Abs.Tvoid -> prPrec i 0 (concatD [doc (showString "void")])

